version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: nginx-conf
        target: /etc/nginx/conf.d
      - type: volume
        source: nginx-vhost
        target: /etc/nginx/vhost.d
      - type: volume
        source: nginx-html
        target: /usr/share/nginx/html
      - type: volume
        source: /usr/local/dockercerts
        target: /etc/nginx/cert
        readonly: true
    environment:
      - VIRTUAL_PORT=${VIRTUAL_PORT}
  nginx-gen:
    image: lantrix/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /usr/local/dockercerts:/etc/nginx/certs
      - /usr/local/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html: